version: "3.1"

services:
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - nextrpc-db:/var/lib/mysql
        ports:
            - 3307:3306
        env_file:
            - ./db.env

    adminer:
        image: adminer
        restart: always
        ports:
            - 7000:8080

volumes:
    nextrpc-db:
